wine_list = {
    "Brut Sparkling Wine" :["semi-dry", "sparkling", "white", "apple", "pear"],
    "Aligote" : ["very dry", "white", "apple", "pear", "light-bodied"],
    "Sauvingnon Blanc" : ["very dry", "white", "gooseberry", "citrus", "light-bodied"],
    "Gewurztraminer" : ["very dry", "white", "floral", "full-bodied", "spice", "tropical"],
    "Barrel Fermented Chardonnay" : ["absolute dry", "white", "berries", "butter", "oak", "full-bodied"],
    "Rose" : ["dry", "strawberry", "rose", "light-bodied"],
    "Gamay Noir" : ["very dry", "red", "cherry", "plum", "berries", "spice", "medium-bodied"],
    "Gamay Noir 'Droit'" : ["very dry", "red", "peppercorn", "cherry", "plum", "berries", "spice", "medium-bodied"],
    "Atelier" : ["dry", "red", "blend", "plum", "berries", "spice", "medium-bodied"],
    "Estate Pinot Noir" : ["very dry", "red", "strawberry", "raspberry", "floral", "mushroom", "medium-bodied"],
    "Estate Cabernet Sauvignon" : ["very dry", "red", "oak", "cherry", "dark chocolate", "spice", "vanilla", "full-bodied"],
    "Cabernet Merlot" : ["very dry", "red", "blend", "oak", "dark chocolate", "raspberry", "full-bodied"],
    "Vidal Icewine" : ["very sweet", "white", "honey", "apricot", "peach", "lychee", "full-bodied"],
    "Rose Sparkling Wine" : ["semi-dry", "sparkling", "floral", "rose", "strawberry", "light-bodied"],
    "Blanc de Blancs Sparkling Wine" : ["absolute dry", "sparkling", "white", "vanilla", "citrus", "toasty"],
    "'Old Vines' Riesling" : ["sweet", "white", "citrus", "mineral", "full-bodied"],
    "'Old Vines' Pinot Noir" : ["very dry", "red", "raspberry", "strawberry", "mushroom", "earthy", "spice", "medium-bodied"],
    "'Old Vines' Cabernet-Merlot" : ["very dry", "red", "oak", "peppercorn", "blend", "cherry", "raspberry", "medium-bodied"],
    "Fume Blanc" : ["absolute dry", "white", "citrus", "oak", "tropical", "full-bodied"],
    "St. Davids Bench Chardonnay" : ["very dry", "white", "oak", "melon", "spice", "berries", "mineral", "full-bodied"],
    "Paul Bosc Chardonnay" : ["very dry", "white", "oak", "butter", "citrus", "melon", "full-bodied"],
    "Paul Bosc Pinot Noir" : ["very dry", "red", "strawberry", "raspberry", "floral", "earthy", "full-bodied"],
    "Merlot" : ["very dry", "red", "cherry", "plum", "dark chocolate", "full-bodied"],
    "Cabernet Franc" : ["very dry", "red", "oak", "peppercorn", "pipe tobacco", "full-bodied"],
    "St. Davids Bench Cabernet Sauvignon" : ["very dry", "red", "oak", "plum", "cherry", "dark chocolate", "peppercorn", "full-bodied"],
    "Equuleus" : ["very dry", "red", "oak", "dark chocolate", "blend", "full-bodied"],
    "Cabernet Icewine" : ["very sweet", "red", "strawberry", "cranberry", "full-bodied"]
}